on:
  push:
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'mobilephone.zip'
        path: './mobilephone/'

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "mobilephone.zip"
